// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentForm.DataBase.DataBase;

#nullable disable

namespace PaymentForm.DataBase.Migrations
{
    [DbContext(typeof(MyAppContext))]
    partial class MyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentForm.DataBase.EfCoreModels.PaymentEfCore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("payments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 123m,
                            Comment = "",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 35, 43, 126, DateTimeKind.Utc).AddTicks(8019),
                            Currency = 1,
                            Email = "user_1@u",
                            Status = 0,
                            WalletId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 1000m,
                            Comment = "",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 35, 43, 127, DateTimeKind.Utc).AddTicks(30),
                            Currency = 3,
                            Email = "user_1@u",
                            Status = 0,
                            WalletId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 123m,
                            Comment = "",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 35, 43, 127, DateTimeKind.Utc).AddTicks(34),
                            Currency = 1,
                            Email = "user_2@u",
                            Status = 0,
                            WalletId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 765m,
                            Comment = "",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 35, 43, 127, DateTimeKind.Utc).AddTicks(53),
                            Currency = 2,
                            Email = "user_3@u",
                            Status = 0,
                            WalletId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 5000m,
                            Comment = "",
                            CreatedAt = new DateTime(2026, 4, 20, 16, 35, 43, 127, DateTimeKind.Utc).AddTicks(56),
                            Currency = 4,
                            Email = "user_4@u",
                            Status = 0,
                            WalletId = 6L
                        });
                });

            modelBuilder.Entity("PaymentForm.DataBase.EfCoreModels.UserEfCore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "user_1@u",
                            Name = "user_1",
                            PhoneNumber = "555-111-3333"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "user_2@u",
                            Name = "user_2",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 3L,
                            Email = "user_3@u",
                            Name = "user_3",
                            PhoneNumber = "123-123-1234"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "user_4@u",
                            Name = "user_4",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("PaymentForm.DataBase.EfCoreModels.WalletEfCore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WalletNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletNumber")
                        .IsUnique();

                    b.ToTable("wallets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Balance = 1235m,
                            UserId = 1L,
                            WalletNumber = "1111"
                        },
                        new
                        {
                            Id = 2L,
                            Balance = 9876m,
                            UserId = 1L,
                            WalletNumber = "2222"
                        },
                        new
                        {
                            Id = 3L,
                            Balance = 4567m,
                            UserId = 2L,
                            WalletNumber = "3333"
                        },
                        new
                        {
                            Id = 4L,
                            Balance = 1234m,
                            UserId = 3L,
                            WalletNumber = "4444"
                        },
                        new
                        {
                            Id = 5L,
                            Balance = 5432m,
                            UserId = 4L,
                            WalletNumber = "5555"
                        },
                        new
                        {
                            Id = 6L,
                            Balance = 7687m,
                            UserId = 4L,
                            WalletNumber = "6666"
                        });
                });

            modelBuilder.Entity("PaymentForm.DataBase.EfCoreModels.PaymentEfCore", b =>
                {
                    b.HasOne("PaymentForm.DataBase.EfCoreModels.WalletEfCore", "WalletEfCore")
                        .WithMany("PaymentsEfCore")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WalletEfCore");
                });

            modelBuilder.Entity("PaymentForm.DataBase.EfCoreModels.WalletEfCore", b =>
                {
                    b.HasOne("PaymentForm.DataBase.EfCoreModels.UserEfCore", "UserEfCore")
                        .WithMany("WalletsEfCore")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEfCore");
                });

            modelBuilder.Entity("PaymentForm.DataBase.EfCoreModels.UserEfCore", b =>
                {
                    b.Navigation("WalletsEfCore");
                });

            modelBuilder.Entity("PaymentForm.DataBase.EfCoreModels.WalletEfCore", b =>
                {
                    b.Navigation("PaymentsEfCore");
                });
#pragma warning restore 612, 618
        }
    }
}
